Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,8 +16,13 @@ jobs:
           override: true
       - name: Install SP1 Toolchain with sp1up
         run: |
-          curl -L https://sp1up.succinct.xyz | bash
-          source ~/.bashrc || source ~/.zshrc # Активируем sp1up
+          curl -L https://sp1up.succinct.xyz | bash -s -- --yes
+          # Активируем изменения в PATH
+          echo "/home/runner/.sp1/bin" >> $GITHUB_PATH
+          echo "/home/runner/.local/bin" >> $GITHUB_PATH
+          # Проверяем, установлен ли sp1up
+          which sp1up || (echo "sp1up not found in PATH"; exit 1)
+          # Запускаем sp1up для установки succinct toolchain и cargo prove
           sp1up
       - name: Verify SP1 Installation
         run: |
